---
- block: # Install ftp for Redhat machines  
    - name: install vsftpd
      package:
        name: "{{ package }}"
        state: present
    - name: enable vsftpd
      service: 
        name: "{{ package }}"
        state: "{{ vsftpd_service_state }}"
        enabled: "{{ vsftpd_service_enabled }}"
      ignore_errors: yes         
  when: ansible_os_family == "RedHat"

- name: Install additional required packages
  yum:
    name: 
      - python3-libselinux 
      - python3-libsemanage 
      - python3-policycoreutils
    state: present

- name: Copy FTP config
  template:
    src: vsftpd.conf
    dest: /etc/vsftpd/vsftpd.conf
  notify:
      - restart vsftpd  

- name: Check_Create Upload directory
  file:
    path: "{{ remote_dir_up }}"
    state: directory
    mode: "{{ mode_pub_up }}"
    recurse: yes

- block: # Selinux configuration on machines
   - name: Set Selinux boolean for Anonimous FTP upload
     seboolean:
       name: "{{ sel_bool_ftpd_anon_write }}"
       state: "{{ ftpd_anon_write_state }}"
       persistent: yes

   - name: Set Selinuxfile context for pub
     sefcontext:
       target: "{{ remote_dir }}"
       setype: public_content_rw_t
       state: present

   - name: Set Selinuxfile context for pub_upload
     sefcontext:
       target: "{{ remote_dir_up }}"
       setype: public_content_rw_t
       state: present

   - name: Apply new file context to filesystem
     ansible.builtin.command: restorecon -F -R -v /var/ftp/pub/upload

  when: ansible_os_family == "RedHat"

- name: Open ftp port
  firewalld:
    port: 20-21/tcp
    permanent: true
    state: enabled









